/* eslint-disable linebreak-style */

module.exports = {
  up: (queryInterface) =>
    queryInterface.bulkInsert("Photos", [
      {
        album_id: 1,
        title: "accusamus beatae ad facilis cum similique qui sunt",
        thumbnailUrl: "https://via.placeholder.com/150/92c952",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 1,
        title: "reprehenderit est deserunt velit ipsam",
        thumbnailUrl: "https://via.placeholder.com/150/771796",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 1,
        title: "officia porro iure quia iusto qui ipsa ut modi",
        thumbnailUrl: "https://via.placeholder.com/150/24f355",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 1,
        title: "culpa odio esse rerum omnis laboriosam voluptate repudiandae",
        thumbnailUrl: "https://via.placeholder.com/150/d32776",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 1,
        title: "natus nisi omnis corporis facere molestiae rerum in",
        thumbnailUrl: "https://via.placeholder.com/150/f66b97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 1,
        title: "accusamus ea aliquid et amet sequi nemo",
        thumbnailUrl: "https://via.placeholder.com/150/56a8c2",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 1,
        title:
          "officia delectus consequatur vero aut veniam explicabo molestias",
        thumbnailUrl: "https://via.placeholder.com/150/b0f7cc",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 1,
        title: "aut porro officiis laborum odit ea laudantium corporis",
        thumbnailUrl: "https://via.placeholder.com/150/54176f",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 1,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 1,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 2,
        title:
          "officia delectus consequatur vero aut veniam explicabo molestias",
        thumbnailUrl: "https://via.placeholder.com/150/b0f7cc",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 2,
        title: "aut porro officiis laborum odit ea laudantium corporis",
        thumbnailUrl: "https://via.placeholder.com/150/54176f",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 2,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 2,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 3,
        title:
          "officia delectus consequatur vero aut veniam explicabo molestias",
        thumbnailUrl: "https://via.placeholder.com/150/b0f7cc",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 3,
        title: "aut porro officiis laborum odit ea laudantium corporis",
        thumbnailUrl: "https://via.placeholder.com/150/54176f",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 3,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 3,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 3,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 4,
        title:
          "officia delectus consequatur vero aut veniam explicabo molestias",
        thumbnailUrl: "https://via.placeholder.com/150/b0f7cc",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 4,
        title: "aut porro officiis laborum odit ea laudantium corporis",
        thumbnailUrl: "https://via.placeholder.com/150/54176f",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 4,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 4,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 4,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 5,
        title:
          "officia delectus consequatur vero aut veniam explicabo molestias",
        thumbnailUrl: "https://via.placeholder.com/150/b0f7cc",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 5,
        title: "aut porro officiis laborum odit ea laudantium corporis",
        thumbnailUrl: "https://via.placeholder.com/150/54176f",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 5,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 5,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 5,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 6,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 6,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 6,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 6,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 7,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 7,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 7,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 7,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 7,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 8,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 8,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 8,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 8,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 8,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 9,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 9,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 9,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 9,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 10,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 10,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 10,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 10,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 10,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 11,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 11,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 11,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 11,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 11,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 12,
        title: "qui eius qui autem sed",
        thumbnailUrl: "https://via.placeholder.com/150/51aa97",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 12,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 12,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 12,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 12,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        album_id: 13,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 13,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 13,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 13,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 13,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 13,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 13,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 13,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 14,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 14,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 15,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 15,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 15,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 15,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        album_id: 16,
        title: "beatae et provident et ut vel",
        thumbnailUrl: "https://via.placeholder.com/150/810b14",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]),
  down: (queryInterface) => queryInterface.bulkDelete("Photos", null, {}),
};
